//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobsEmployes = new HashSet<JobsEmploye>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public int Type { get; set; }
        public bool IsAdvanceLiquidation { get; set; }
        public Nullable<int> MinimumExperience { get; set; }
        public string Duration { get; set; }
        public long Id_Employee { get; set; }
        public Nullable<long> Id_Job_Employees { get; set; }
        public Nullable<long> Id_Accepted_Employee { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<JobsEmploye> JobsEmployes { get; set; }
    }
}
